version: '3.8'

services:
  jenkins:
    image: my_jenkins_image
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      JENKINS_ADMIN_ID: suhail_admin
      JENKINS_ADMIN_PASSWORD: suhail_jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
    driver: bridge
